### ISSUE TITLE
Error when using Bartlett's test for homoscedacity of normally distributed data

### ISSUE THREAD

**Issue by hadarshavit** [sherbold/autorank#16]
When I run
```python
autorank(df, alpha=0.05, verbose=True)
``` 
On the following dataframe:
| in            |      F1 |     F2 |    F3 |
|:-----------------|----------:|-------------:|-------------:|
| 1        | -0.108493 | -0.182625    | -0.217593    |
| 2 |  0.100764 |  0.170489    | -0.0353945   |
| 3        |  0.578502 |  0.60399     |  0.592368    |
| 4          |  0.690802 |  0.746536    |  0.70053     |
| 5       |  0.280736 |  0.269668    |  0.278789    |
| 6       |  0.43442  |  0.371632    |  0.425941    |
| 7       |  0.568025 |  0.498394    |  0.458875    |
| 8         |  0.952764 |  0.95084     |  0.949877    |
| 9         |  0.339497 |  0.211892    |  0.337175    |
| 10 | -0.334314 |  1.03841e-14 |  1.03841e-14 |
| 11       |  0.7448   |  0.711472    |  0.74447     |
| 12       |  0.946012 |  0.945422    |  0.950613    |
| 13       |  0.317754 |  0.509453    |  0.354345    |

where in is the index of the dataframe, I get the following error:

```
Fail to reject null hypothesis that data is normal for column F1(p=0.799397>=0.016667)
Fail to reject null hypothesis that data is normal for column F2 (p=0.910572>=0.016667)
Fail to reject null hypothesis that data is normal for column F3 (p=0.754639>=0.016667)
Using Bartlett's test for homoscedacity of normally distributed data
Fail to reject null hypothesis that all variances are equal (p=0.946143>=0.050000)
Traceback (most recent call last):
  File "/home/s3092593/afaslib/autofolio/generate_closed_gap_figures.py", line 69, in <module>
    res_without_fc = autorank(df_without_fc, alpha=0.05, verbose=True)
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/autorank/autorank.py", line 278, in autorank
    res = rank_multiple_normal_homoscedastic(data, alpha, verbose, order, effect_size, force_mode)
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/autorank/_util.py", line 254, in rank_multiple_normal_homoscedastic
    anova = AnovaRM(stacked_data, 'result', 'id', within=['treatment'])
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/statsmodels/stats/anova.py", line 496, in __init__
    if not data.equals(data.drop_duplicates(subset=[subject] + within)):
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/pandas/core/frame.py", line 6661, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/home/s3092593/miniconda3/envs/torch/lib/python3.10/site-packages/pandas/core/frame.py", line 6795, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['id'], dtype='object')
```

**Comment by e10e3** [comment]
Hello @sherbold,

I was able to reproduce this error when my dataframe has a custom index.

In Hadar's case, I believe the column "in" was the index of the dataframe. You can reproduce the crash with this code:
```python3
import pandas as pd
from autorank import autorank

data = pd.DataFrame().from_dict({
            'in': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
            'F1': [-0.108493, 0.100764, 0.578502, 0.690802, 0.280736, 0.43442, 0.568025, 0.952764, 0.339497, -0.334314, 0.7448, 0.946012, 0.317754],
            'F2': [-0.182625, 0.170489, 0.60399, 0.746536, 0.269668, 0.371632, 0.498394, 0.95084, 0.211892, 1.03841e-14, 0.711472, 0.945422, 0.509453],
            'F3': [-0.217593, -0.0353945, 0.592368, 0.70053, 0.278789, 0.425941, 0.458875, 0.949877, 0.337175, 1.03841e-14, 0.74447, 0.950613, 0.354345]
        })
data = data.set_index("in") # The column "in" becomes the index
res = autorank(data, 0.05, True)
```

**Comment by sherbold** [comment]
Ah, thanks. Yes, any named index trips autorank up. I guess the same applies to MultiIndex. I will fix this later today.

**Comment by sherbold** [comment]
The bug should now be fixed
